import { AnimationClip } from "../lib/animation";
export declare const idle: AnimationClip;
export declare const idleLeft: AnimationClip;
export declare const walk: AnimationClip;
export declare const walkLeft: AnimationClip;
export declare const walkBack: AnimationClip;
export declare const walkBackLeft: AnimationClip;
export declare const die: AnimationClip;
export declare const dieLeft: AnimationClip;
export declare const block: AnimationClip;
export declare const blockLeft: AnimationClip;
